hydra:  
  output_subdir: null  
  run:  
    dir: .
    
defaults:
  - process: process_2
  - segment: KMeans
  - _self_

raw_data: 
  path: data/raw/marketing_campaign.csv

intermediate:
  dir: data/intermediate
  name: scale_features.csv
  path: ${intermediate.dir}/${intermediate.name}

segmented:
  dir: data/final
  name: segmented.csv
  path: ${segmented.dir}/${segmented.name}

flow: all 

pca:
  n_components: 3
  columns:
  - col1
  - col2
  - col3

image:
  elbow: image/elbow.png
  clusters: image/cluster.png
